# Generated by Django 4.2.7 on 2023-12-31 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_rename_name_book_title_book_borrowed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="endDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 14, 11, 21, 54, 408053)
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
