# Generated by Django 4.2.7 on 2023-12-31 11:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_borrow_enddate_alter_borrow_user_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrow",
            name="endDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 14, 12, 40, 23, 384805)
            ),
        ),
    ]
