# Generated by Django 4.2.8 on 2024-01-02 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_book_options_book_created_alter_borrow_enddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="endDate",
            field=models.DateField(default=datetime.date(2024, 1, 16)),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="startDate",
            field=models.DateField(auto_now_add=True),
        ),
    ]
